const express=require('express');
const adminRouter= require('./routes/adminRouter');
const authRouter = require("./routes/authRouter");
const staffRouter=require('./routes/staffRouter');
const app=express();
app.use(express.json());
app.use('/api/admin',adminRouter);
app.use('/api',authRouter);
app.use('/api/staff',staffRouter);
app.listen(3000);